prompt PL/SQL Developer import file
prompt Created on 2016年5月28日 by Administrator
set feedback off
set define off
prompt Disabling triggers for CONTRACT_C...
alter table CONTRACT_C disable all triggers;
prompt Disabling triggers for CONTRACT_PRODUCT_C...
alter table CONTRACT_PRODUCT_C disable all triggers;
prompt Disabling triggers for EXT_CPRODUCT_C...
alter table EXT_CPRODUCT_C disable all triggers;
prompt Disabling triggers for FACTORY_C...
alter table FACTORY_C disable all triggers;
prompt Disabling triggers for SYS_CODE_B...
alter table SYS_CODE_B disable all triggers;
prompt Deleting SYS_CODE_B...
delete from SYS_CODE_B;
commit;
prompt Deleting FACTORY_C...
delete from FACTORY_C;
commit;
prompt Deleting EXT_CPRODUCT_C...
delete from EXT_CPRODUCT_C;
commit;
prompt Deleting CONTRACT_PRODUCT_C...
delete from CONTRACT_PRODUCT_C;
commit;
prompt Deleting CONTRACT_C...
delete from CONTRACT_C;
commit;
prompt Loading CONTRACT_C...
prompt Table is empty
prompt Loading CONTRACT_PRODUCT_C...
prompt Table is empty
prompt Loading EXT_CPRODUCT_C...
prompt Table is empty
prompt Loading FACTORY_C...
insert into FACTORY_C (FCATORY_ID, FULL_NAME, FACTORY_NAME, CONTACTS, PHONE, MOBILE, FAX, CNOTE, INSPECTOR, ORDER_NO, STATE, CREATE_BY, CREATE_DEPT, CREATE_TIME)
values ('3ad29304-a8a7-4d62-92ea-747d2e0487d5', '璐璐', '陆陆', '了哦', '饿', '饿', '2 ', '亿元', ' 饿', 2, '1', null, null, null);
insert into FACTORY_C (FCATORY_ID, FULL_NAME, FACTORY_NAME, CONTACTS, PHONE, MOBILE, FAX, CNOTE, INSPECTOR, ORDER_NO, STATE, CREATE_BY, CREATE_DEPT, CREATE_TIME)
values ('94e4881c-a63d-43e9-b664-359b3ce87bef', '1', '2', '3', '4', '5', '6', '9' || chr(13) || '' || chr(10) || '0', '7', 8, '1', null, null, null);
commit;
prompt 2 records loaded
prompt Loading SYS_CODE_B...
prompt Table is empty
prompt Enabling triggers for CONTRACT_C...
alter table CONTRACT_C enable all triggers;
prompt Enabling triggers for CONTRACT_PRODUCT_C...
alter table CONTRACT_PRODUCT_C enable all triggers;
prompt Enabling triggers for EXT_CPRODUCT_C...
alter table EXT_CPRODUCT_C enable all triggers;
prompt Enabling triggers for FACTORY_C...
alter table FACTORY_C enable all triggers;
prompt Enabling triggers for SYS_CODE_B...
alter table SYS_CODE_B enable all triggers;
set feedback on
set define on
prompt Done.
